MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.fpn_ResNet152_conv5_body
  NUM_CLASSES: 13
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0001
  GAMMA: 0.1
  MAX_ITER: 260000
  STEPS: [0, 200000, 240000]
FPN: 
  FPN_ON: True
  MULTILEVEL_RPN: True
  # RPN_MAX_LEVEL: 7
  # RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True

RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25

RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/X-152-32x8d-IN5k.pkl'
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 32
  WIDTH_PER_GROUP: 8
  
TRAIN:
  SCALES: (800,)  # Scale jitter
  MAX_SIZE: 1333
  RPN_STRADDLE_THRESH: -1
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  